### ISSUE TITLE
Usage in combination with spatie/laravel-translation-loader

### ISSUE THREAD

**Issue by gizburdt** [kirschbaum-development/laravel-translations-loader#40]
Hi,

Awesome package and works like a charm! Since a while we are using spatie/laravel-translation-loader, so the translations are stored in the database, for better management of alle strings. But now I'm not really sure how to load these translations from the database in this package. Do you have experience with the combination of these two packages?

Thanks :)

**Comment by luisdalmolin** [comment]
Hmm, it's a great question. This in theory won't be really possible without a lot of work and configuration because this package reads from the actual files at build time, and at this point, you may not have access to the database depending on where you are building the assets, and we would have to make NodeJS talk with the database, etc. So no plans at this point to support this, sorry.

**Comment by gizburdt** [comment]
No problem, thanks for the reply :)
